name: Build & Deploy Android App to EC2

on:
  push:
    branches: ["main"]  # Make sure this matches your branch name
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Build Android App
      run: |
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build -t "${{ secrets.DOCKER_USERNAME }}/android-camera-app:latest" .
        docker push "${{ secrets.DOCKER_USERNAME }}/android-camera-app:latest"

    - name: SSH to EC2 and Deploy Android App
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_USERNAME_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # Stop and remove existing container if running
          docker ps -q --filter "name=android-camera" | grep -q . && docker stop android-camera && docker rm android-camera || echo "No running container"

          # Remove previous
