name: Build & Deploy Android App to EC2

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Build Android App
      run: |
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build -t "${{ secrets.DOCKER_USERNAME }}/android-camera-app:latest" .
        docker push "${{ secrets.DOCKER_USERNAME }}/android-camera-app:latest"

    - name: SSH to EC2 and Deploy Android App
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_USERNAME_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # Stop and remove any running containers with this name
          docker stop android-camera || true
          docker rm android-camera || true

          # Remove old image
          docker rmi "${{ secrets.DOCKER_USERNAME }}/android-camera-app:latest" || true

          # Run the new container
          docker run -t --name android-camera "${{ secrets.DOCKER_USERNAME }}/android-camera-app:latest"

          # Optional: Copy APK from container to EC2 host (for download or distribution)
          docker cp android-camera:/serve/app-debug.apk /home/ubuntu/app-debug.apk
